import { describe, expect, it } from 'vitest';
import { generateSeed } from '../src/seed.js';
import { buildDayPlan } from '../src/engine/plan.js';
import { baseSettings, program, rules } from './helpers.js';

describe('sample data', () => {
  const data = generateSeed(program, rules, '2026-09-29');

  it('covers 3 full weeks before the current one, all marked as seed', () => {
    expect(data.bodyMetrics).toHaveLength(21);
    expect(data.bodyMetrics[0].date).toBe('2026-09-07');
    expect(data.bodyMetrics[20].date).toBe('2026-09-27');
    expect(data.sessions).toHaveLength(21);
    for (const t of Object.values(data)) for (const r of t) expect(r.seed).toBe(true);
  });

  it('shows real progressions generated by the engine', () => {
    const bench = data.sessions.filter((s) => s.programDayId === 'upperA').map((s) => s.entries.find((e) => e.exerciseId === 'bench_bb').sets[0].weightKg);
    expect(bench[bench.length - 1]).toBeGreaterThan(bench[0]);
  });

  it('produces targets for today from the seeded history', () => {
    const plan = buildDayPlan({ program, rules, settings: baseSettings(), date: '2026-10-05', sessions: data.sessions });
    expect(plan.blocks[0].target.weightKg).toBeGreaterThan(0);
    expect(plan.ramp.sets[0].weightKg).toBe(20);
  });

  it('the last match (pain 4) triggers the injury adjustments', () => {
    const plan = buildDayPlan({ program, rules, settings: baseSettings(), date: '2026-09-30', sessions: data.sessions });
    expect(plan.blocks.find((b) => b.id === 'L1').skippedForInjury).toBe(true);
  });
});
