// Sample data: 3 full weeks before the current one, every row marked `seed: true`.
// Loads are generated by the real progression engine so charts show real behaviour.
import { addDays, mondayOf, todayISO } from './engine/dates.js';
import { prescribeDay, snapshotPrescription } from './engine/prescription.js';
import { exerciseHistory, nextTarget } from './engine/progression.js';
import { weekSummary } from './engine/weekly.js';

const START_LOADS = {
  bench_bb: 60, row_bb: 55, incline_db: 20, lat_pulldown_wide: 50, lateral_raise_cable: 5, face_pull: 20, curl_ez: 25,
  pushdown_rope: 20, shrug_bb: 80, squat_bb: 80, rdl_bb: 70, leg_press: 140, hip_thrust_bb: 80, calf_standing: 60,
  farmers_carry: 24, pallof_press: 15, cable_crunch: 30, ohp_bb: 40, pullup: 25, bench_db: 22, row_db_1arm: 26,
  lateral_raise_db: 8, rear_delt_pecdeck: 30, incline_db_curl: 10, overhead_ext_cable: 20, wrist_curl: 12, reverse_curl: 20,
  pec_deck: 45, pulldown_neutral: 50, lateral_raise_machine: 20, shrug_db: 30, neck_flex_ext: 5, hammer_curl: 12,
};

// Deterministic pseudo-random (mulberry32).
function rng(seed) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const PAIN = {
  padelTech: [[2, 1], [2, 1], [1, 0]],
  padelMatch: [3, 2, 4],
  lower: [1, 1, 2],
};

export function generateSeed(program, rules, today = todayISO()) {
  const rand = rng(42);
  const start = addDays(mondayOf(today), -21);
  const sessions = [];
  const bodyMetrics = [];
  const nutrition = [];
  const bonus = {};

  for (let d = 0; d < 21; d++) {
    const date = addDays(start, d);
    const week = Math.floor(d / 7);
    const blockWeek = week + 1;
    const day = program.days.find((x) => x.weekday === (d % 7) + 1);

    // Morning metrics
    const m = {
      date,
      weightKg: Math.round((89.3 - d * 0.02 + (rand() - 0.5) * 0.8) * 10) / 10,
      sleepH: Math.round((6.8 + rand() * 1.2) * 10) / 10,
      restingHR: Math.round(54 + rand() * 4),
      seed: true,
    };
    if (d === 6 || d === 20) {
      Object.assign(m, d === 6
        ? { waistCm: 93.2, neckCm: 40, shouldersCm: 121, chestCm: 103, armFlexedCm: 36.5, thighCm: 60 }
        : { waistCm: 92.3, neckCm: 40.2, shouldersCm: 122, chestCm: 103.5, armFlexedCm: 37, thighCm: 60 });
    }
    bodyMetrics.push(m);

    const padel = rules.nutrition.padelDayTypes.includes(day.type);
    nutrition.push({
      date,
      kcal: Math.round((padel ? 2600 : 2850) + (rand() - 0.5) * 300),
      proteinG: Math.round(170 + rand() * 25),
      carbsG: Math.round((padel ? 280 : 340) + (rand() - 0.5) * 40),
      fatG: Math.round(80 + (rand() - 0.5) * 20),
      creatineTaken: rand() > 0.1,
      steps: Math.round(7000 + rand() * 5000),
      seed: true,
    });

    const base = { date, programDayId: day.id, dayType: day.type, blockWeek, deload: false, status: 'done', seed: true, entries: [], warmupDone: {}, checklist: {}, rehabDone: {} };

    if (day.type === 'padelTech' || day.type === 'padelMatch') {
      const idx = day.type === 'padelTech' ? (day.weekday === 2 ? 0 : 1) : 0;
      const pain = day.type === 'padelTech' ? PAIN.padelTech[week][idx] : PAIN.padelMatch[week];
      sessions.push({
        ...base,
        durationMin: day.type === 'padelMatch' ? 110 : 80,
        groinPain0to10: pain,
        groinPainOver24h: false,
        feeling1to10: 7,
        sleepH: day.type === 'padelMatch' ? 7.2 : undefined,
        kbExtraDone: day.type === 'padelTech' && week !== 1,
        checklist: Object.fromEntries((day.checklist || []).map((c) => [c.id, true])),
      });
      continue;
    }

    const plan = prescribeDay(program, rules, day.id, blockWeek);
    const s = { ...base, durationMin: 80 + Math.round(rand() * 10), feeling1to10: 7 + Math.round(rand() * 2), checklist: { walk: true } };
    if (day.type === 'lower') {
      s.groinPain0to10 = PAIN.lower[week];
      s.groinPainOver24h = false;
      s.rehabDone = Object.fromEntries(program.rehab.steps[0].items.map((i) => [i.id, true]));
    }
    for (const b of plan.blocks) {
      if (b.kind === 'rehab') continue;
      const ex = program.exercises.find((e) => e.id === b.exerciseId);
      const history = exerciseHistory(sessions, ex.id, day.id, date);
      const target = nextTarget({ exercise: ex, prescribed: b, history, rules, today: date });
      const load = target.weightKg ?? START_LOADS[ex.id] ?? 20;
      if (target.action === 'increase' || target.action === 'reduce') bonus[ex.id] = 0;
      const k = bonus[ex.id] || 0;
      const sets = [];
      for (let i = 0; i < b.sets; i++) {
        const noise = k === 0 && i >= 2 && rand() < 0.5 ? -1 : 0;
        const reps = Math.max(b.repRange.min - 1, Math.min(b.repRange.max, b.repRange.min + 1 + k + noise));
        const rpe = reps >= b.repRange.max ? Math.max(6, b.rpeTarget.max - 0.5) : b.rpeTarget.max;
        sets.push({ weightKg: load, reps, rpe, technique: 'none' });
      }
      bonus[ex.id] = k + 3;
      s.entries.push({ blockId: b.id, exerciseId: ex.id, prescribed: snapshotPrescription(b), sets, notes: '' });
    }
    sessions.push(s);
  }

  const weeklyChecks = [0, 1, 2].map((w) => {
    const ws = addDays(start, w * 7);
    const sum = weekSummary({ weekStart: ws, sessions, metrics: bodyMetrics, program });
    return { ...sum, proposedDecisions: [], confirmedDecisions: [], dismissedDecisions: [], blockWeek: w + 1, seed: true };
  });

  return { sessions, bodyMetrics, nutrition, weeklyChecks };
}

// Inserts sample rows without touching real data (existing dates/sessions are skipped).
export async function loadSeed(program, rules) {
  const { db, getSessionFor } = await import('./db.js');
  const data = generateSeed(program, rules);
  let n = 0;
  for (const s of data.sessions) {
    if (await getSessionFor(s.date, s.programDayId)) continue;
    await db.sessions.add(s);
    n++;
  }
  for (const t of ['bodyMetrics', 'nutrition']) {
    for (const r of data[t]) {
      if (await db[t].get(r.date)) continue;
      await db[t].add(r);
      n++;
    }
  }
  for (const c of data.weeklyChecks) {
    if (await db.weeklyChecks.get(c.weekStart)) continue;
    await db.weeklyChecks.add(c);
    n++;
  }
  return n;
}
